# Generated by Django 4.2.29 on 2026-03-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinquiry',
            name='submission_type',
            field=models.CharField(choices=[('inquiry', 'Contact Inquiry'), ('ats_resume', 'ATS Resume Form'), ('combo_pack', 'Combo Pack Form'), ('custom_project', 'Custom Project Form')], default='inquiry', max_length=20),
        ),
    ]
