# Generated by Django 4.2.29 on 2026-04-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactinquiry_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinquiry',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('completed', 'Completed'), ('spam', 'Spam')], db_index=True, default='new', max_length=20),
        ),
    ]
